### ISSUE TITLE
Improve animation of tool cost over time

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/data-analysis-tools-cost#1]
Follow [model of John Burn-Murdoch](https://twitter.com/jburnmurdoch/status/1347200811303055364).

- Have it go one line at a time, one for each tool
- Have the title of the tool show up at top while it's going
- Have the final cost after 5 years show up to right of line (but no need to show number before this)
- Don't worry about having y axis adjust like in the John Burn-Murdoch one

**Comment by MaiaPelletier** [comment]
Hey @dgkeyes ! I just wanted to let you know that I've been working away at this but it's not super straightforward. I know you said you were thinking by the end of the week for it but I don't think I'll be able to have it done by tomorrow.

**Comment by dgkeyes** [comment]
Thanks for the update! At this point, if it's just going to be too complicated, let's not worry about it. I'd like to improve the viz, but it's fine as is now.

**Comment by MaiaPelletier** [comment]
Sounds good. I'll push my code with the work I've done on it up to this point.

**Comment by dgkeyes** [comment]
Anywhere in particular you were running into problems?

**Comment by MaiaPelletier** [comment]
It was the revealing the lines one at a time. As far as I can tell (from my work on it this weekend), it seems that you can reveal the groups one at a time using `transition_states()` (or `transition_time()`) but that doesn't allow for a `transition_reveal()` along the x_axis. I tried to use `shadow_mark()` to create the lines for the past data while using `transition_reveal()` but it seems that `shadow_mark()` only works for transitioning between discrete states. [Gif #1](https://i.imgur.com/LHCd1s5.gif) shows the `transition_reveal` (with an adjustable y-axis like the John Burn-Murdoch viz) and [gif #2](https://i.imgur.com/07Tr9Q4.gif) displays each group one at a time using `shadow_mark()` and `transition_states()`. The trouble was figuring out how to "combine"  or create a workaround that functions similarly to both of the transitions to create the John-Burn Murdoch model.

I reached out for help on the R4ds Slack and I have yet to find a solution/something to point me in the direction of a solution. There was this [post ](https://stackoverflow.com/questions/63723797/animating-only-one-line-and-two-static-lines-in-a-plot-with-gganimate) on StackOverflow but I wasn't able to translate it to multiple group reveals.

**Comment by dgkeyes** [comment]
Ok, thanks. I'll take a look and see if I can figure anything else out. Thanks for trying!

**Comment by MaiaPelletier** [comment]
@dgkeyes I know we said to leave it for now but I got a response on the R4DS that really helped and I was able to get each line to reveal one at a time. I just pushed the new code and the "correct" animation with all the improvements you wanted is [here](https://github.com/rfortherestofus/data-analysis-tools-cost/blob/master/cost-over-time2.gif). The solution was so simple it's actually a little frustrating lol - it was to have a unique index for the data to reveal over. Let me know if you're interested in the details, I got a really great response from the R user I was corresponding with!

I know it's later than you asked for it but I still hope that this helps!

**Comment by dgkeyes** [comment]
That's awesome! I'll plug it in this morning. Thanks so much!

**Comment by dgkeyes** [comment]
Looks great! I made just a few small tweaks. Thanks again. 

Please put whatever time you worked on it into the "Internal" project on Toggl. It's a "public" project so I believe you should have access to it without me explicitly adding you.

**Comment by MaiaPelletier** [comment]
Closing this to clear out my github inbox 🙂
